### ISSUE TITLE
'Blank' return for unknown queries

### ISSUE THREAD

**Issue by Adrian-Pop** [detectlanguage/detectlanguage-java#5]
After making a query for an entire list, I noticed some returns were completely empty, only returning a '[' in the JSON, which makes it hard to handle and check for sizing.

The examples I tested it with are these: 

> pwd, bccl, kinlay, lotay, dopshari, gaupay, dargay, helvetas, cdb, pangray, bijay, chojay, sanjay, td, yargay, dcd, gortab, helvatas, jurmay, kaflay, namsay, bg, chungdruk, draftman, gynecologist, mangjay, minjay, nakphay, norbooz, surjay, agrewal, allaway, apecs, bagdogra, bajay, bokray, bumdrag, changchay, chejay, chenray, chotay, dd, dhopshari, dtl, echay, emssd, fd, fsd, gajay, ganglue, gaygay, gaypay, gopay, gunjay, halvetas, hideway, hoilday, hungrap, iffch, jamgay, js, jungnay, karpay, kharl, lakshay, lingshay, lunjay, mafchan, malabasay, mso, nangsay, naphay, ninjay, pelgay, phojay, ramashray, ratney, ropeway, sarswati, sujay, sumjay, swapan, tenshay, thajay, thenpay, thsewang, tlt, tobjay, trk, tshejay, wanjay, yongdrag, aircraf, lubzor

A demo return on 'pwd' is also empty http://ws.detectlanguage.com/0.2/detect?q[]=pwd&key=demo

The JSON response for the first 2 is
`{
  "data": {
    "detections": [
      [],
      []
    ]
  }
}`

**Comment by laurynas** [comment]
Yes, API returns empty result if language can't be detected. 

Your `pwd` example uses batch request (`q[]` param) therefore result is nested:
`{"data":{"detections":[[]]}}`

If you would simple `q=pwd` param, then result wouldn't be nested. Example:
http://ws.detectlanguage.com/0.2/detect?q=pwd&key=demo
`{"data":{"detections":[]}}`

Just a note - I recommend using POST instead of GET requests. GET is good for linking test examples, just like you did, but for the real implementation POST is the way to go.
